import jpeg from 'npm:jpeg-js@0.4.4';
import {PNG} from 'npm:pngjs@7.0.0';

const ALLOWED_ORIGIN=/^(https:\/\/sindhorn-midtown-internal\.pages\.dev|https:\/\/[a-z0-9-]+\.sindhorn-midtown-internal\.pages\.dev)$/i;
const CATALOG_URL='https://opencctv.org/cameras/thailand/bangkok';
const CATALOG_TTL_MS=20*60_000;
const FRAME_TTL_MS=2*60_000;
const PAGE_TIMEOUT_MS=4500;
const FRAME_TIMEOUT_MS=5000;
const MAX_FRAME_BYTES=4*1024*1024;
const MAX_ANALYSED_IMAGE_CAMERAS=16;

type Camera={id:string|null,name:string,pageUrl:string,lat:number,lon:number,feedType:string,directFeedUrl:string|null,sourceHost:string|null,live:boolean,refreshText:string|null,distanceKm?:number};
type CameraCatalog={fetchedAt:string,cameras:Camera[]};
type FrameAnalysis={fetchedAt:string,cameraId:string|null,width:number,height:number,meanLuma:number,contrast:number,topLuma:number,topLowSaturationRatio:number,reflectionRatio:number,streakLikeRatio:number,visualRainScore:number,classification:'wet-candidate'|'dry-candidate'|'inconclusive',quality:'usable'|'low-light'|'low-contrast'|'invalid'};
type Cache<T>={expiresAt:number,value:T};

let catalogCache:Cache<CameraCatalog>|null=null;
const frameCache=new Map<string,Cache<FrameAnalysis>>();

function cors(origin:string|null){return{'Access-Control-Allow-Origin':origin&&ALLOWED_ORIGIN.test(origin)?origin:'https://sindhorn-midtown-internal.pages.dev','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST,OPTIONS','Vary':'Origin'}}
function json(data:unknown,status=200,origin:string|null=null){return new Response(JSON.stringify(data),{status,headers:{...cors(origin),'content-type':'application/json; charset=utf-8','cache-control':'private, no-store'}})}
function clamp(value:number,min=0,max=1){return Math.min(max,Math.max(min,value))}
function finite(value:unknown,min:number,max:number){const n=Number(value);return Number.isFinite(n)&&n>=min&&n<=max?n:null}
function haversineKm(lat1:number,lon1:number,lat2:number,lon2:number){const rad=Math.PI/180,dLat=(lat2-lat1)*rad,dLon=(lon2-lon1)*rad,a=Math.sin(dLat/2)**2+Math.cos(lat1*rad)*Math.cos(lat2*rad)*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
async function timedFetch(input:RequestInfo|URL,timeoutMs:number,init:RequestInit={}){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(input,{...init,signal:controller.signal})}finally{clearTimeout(timeout)}}
function decodeEntities(value:string){return value.replaceAll('&amp;','&').replaceAll('&quot;','"').replaceAll('&#39;',"'").replaceAll('&lt;','<').replaceAll('&gt;','>')}
function stripTags(value:string){return decodeEntities(value.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim()}
function absoluteUrl(base:string,value:string){try{const url=new URL(decodeEntities(value),base);return /^https?:$/.test(url.protocol)?url.href:null}catch(_){return null}}
function cameraLinks(html:string){const links=new Set<string>();for(const match of html.matchAll(/href=["']([^"']+)["']/gi)){const href=absoluteUrl(CATALOG_URL,match[1]);if(!href)continue;try{const url=new URL(href);const parts=url.pathname.split('/').filter(Boolean);if(url.hostname==='opencctv.org'&&parts[0]==='cameras'&&parts[1]==='thailand'&&parts[2]==='bangkok'&&parts.length>=5)links.add(url.origin+url.pathname)}catch(_){}}return [...links]}
function directFeed(html:string,pageUrl:string){for(const match of html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const text=stripTags(match[2]).toLowerCase();if(!text.includes('open feed url')&&!text.includes('try direct link'))continue;const url=absoluteUrl(pageUrl,match[1]);if(url)return url}return null}
function parseCamera(html:string,pageUrl:string):Camera|null{const text=stripTags(html);const titleMatch=html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i),name=titleMatch?stripTags(titleMatch[1]):'Bangkok public camera';const coord=text.match(/Coordinates\s+(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)/i);if(!coord)return null;const lat=finite(coord[1],-90,90),lon=finite(coord[2],-180,180);if(lat===null||lon===null)return null;const feed=text.match(/Feed Type\s+(IMAGE|IFRAME|HLS|MJPEG|VIDEO)/i)?.[1]?.toUpperCase()||'UNKNOWN';const id=text.match(/Camera ID\s+(\d+)/i)?.[1]||pageUrl.match(/-(\d+)(?:\/)?$/)?.[1]||null;const direct=directFeed(html,pageUrl);const refresh=text.match(/(?:refreshes|refresh)\s+(?:approximately\s+)?(?:about\s+)?(?:every\s+)?([^\.]{1,60})\./i)?.[1]?.trim()||null;let sourceHost:string|null=null;try{sourceHost=direct?new URL(direct).hostname:null}catch(_){sourceHost=null}return{id,name,pageUrl,lat,lon,feedType:feed,directFeedUrl:direct,sourceHost,live:/\bLive\b/i.test(text.slice(0,350)),refreshText:refresh}}
async function mapLimit<T,R>(items:T[],limit:number,fn:(item:T)=>Promise<R>):Promise<R[]>{const out=new Array<R>(items.length);let next=0;async function worker(){while(true){const i=next++;if(i>=items.length)return;out[i]=await fn(items[i])}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
async function buildCatalog(){const now=Date.now();if(catalogCache&&catalogCache.expiresAt>now)return{...catalogCache.value,cache:'hit'};const pages=[CATALOG_URL,`${CATALOG_URL}?page=2`,`${CATALOG_URL}?page=3`];const pageHtml=await Promise.all(pages.map(async url=>{try{const r=await timedFetch(url,PAGE_TIMEOUT_MS,{headers:{'user-agent':'SindhornMidtownInternalCameraWeatherLab/1.0'}});return r.ok?await r.text():''}catch(_){return''}}));const links=[...new Set(pageHtml.flatMap(cameraLinks))];const parsed=await mapLimit(links,8,async pageUrl=>{try{const r=await timedFetch(pageUrl,PAGE_TIMEOUT_MS,{headers:{'user-agent':'SindhornMidtownInternalCameraWeatherLab/1.0'}});if(!r.ok)return null;return parseCamera(await r.text(),pageUrl)}catch(_){return null}});const cameras=parsed.filter((value):value is Camera=>Boolean(value));const value={fetchedAt:new Date().toISOString(),cameras};catalogCache={expiresAt:now+CATALOG_TTL_MS,value};return{...value,cache:'miss'} }
function decodeImage(bytes:Uint8Array,contentType:string){if(/png/i.test(contentType)||bytes[0]===0x89&&bytes[1]===0x50){const png=PNG.sync.read(bytes);return{width:png.width,height:png.height,data:new Uint8Array(png.data.buffer,png.data.byteOffset,png.data.byteLength)}}const decoded=jpeg.decode(bytes,{useTArray:true});if(!decoded?.width||!decoded?.height||!decoded?.data)throw new Error('image_decode_failed');return{width:decoded.width,height:decoded.height,data:new Uint8Array(decoded.data.buffer,decoded.data.byteOffset,decoded.data.byteLength)}}
function analysePixels(camera:Camera,image:{width:number,height:number,data:Uint8Array}):FrameAnalysis{const {width,height,data}=image;if(width<32||height<24)throw new Error('image_too_small');const step=Math.max(1,Math.floor(Math.sqrt((width*height)/36_000)));let count=0,sum=0,sumSq=0,topCount=0,topSum=0,topLowSat=0,lowerCount=0,reflection=0,edgeCount=0,streakLike=0;const idx=(x:number,y:number)=>(y*width+x)*4;const lumAt=(x:number,y:number)=>{const i=idx(x,y);return .2126*data[i]+.7152*data[i+1]+.0722*data[i+2]};for(let y=step;y<height-step;y+=step){for(let x=step;x<width-step;x+=step){const i=idx(x,y),r=data[i],g=data[i+1],b=data[i+2],lum=.2126*r+.7152*g+.0722*b,max=Math.max(r,g,b),min=Math.min(r,g,b),sat=max-min;count++;sum+=lum;sumSq+=lum*lum;if(y<height*.38){topCount++;topSum+=lum;if(sat<28)topLowSat++}if(y>height*.56){lowerCount++;if(lum>165&&sat<36)reflection++}const gx=Math.abs(lumAt(x+step,y)-lumAt(x-step,y)),gy=Math.abs(lumAt(x,y+step)-lumAt(x,y-step));edgeCount++;if(gx>34&&gy<18&&lum>30)streakLike++}}const mean=sum/Math.max(1,count),variance=Math.max(0,sumSq/Math.max(1,count)-mean*mean),contrast=Math.sqrt(variance),topLuma=topSum/Math.max(1,topCount),topLowSaturationRatio=topLowSat/Math.max(1,topCount),reflectionRatio=reflection/Math.max(1,lowerCount),streakLikeRatio=streakLike/Math.max(1,edgeCount);let quality:FrameAnalysis['quality']='usable';if(mean<28)quality='low-light';else if(contrast<10)quality='low-contrast';let score=streakLikeRatio*5.8+reflectionRatio*1.15+(topLuma<105?.11:0)+(contrast<38?.07:0)+(topLowSaturationRatio>.72?.05:0);if(quality==='low-light')score*=.55;if(quality==='low-contrast')score*=.7;score=clamp(score);let classification:FrameAnalysis['classification']='inconclusive';if(quality==='usable'&&score>=.66&&streakLikeRatio>.045)classification='wet-candidate';else if(quality==='usable'&&score<=.18&&topLuma>70&&streakLikeRatio<.018)classification='dry-candidate';return{fetchedAt:new Date().toISOString(),cameraId:camera.id,width,height,meanLuma:Number(mean.toFixed(1)),contrast:Number(contrast.toFixed(1)),topLuma:Number(topLuma.toFixed(1)),topLowSaturationRatio:Number(topLowSaturationRatio.toFixed(3)),reflectionRatio:Number(reflectionRatio.toFixed(3)),streakLikeRatio:Number(streakLikeRatio.toFixed(3)),visualRainScore:Number(score.toFixed(3)),classification,quality}}
async function analyseCamera(camera:Camera){const key=camera.directFeedUrl||camera.pageUrl,now=Date.now(),hit=frameCache.get(key);if(hit&&hit.expiresAt>now)return{camera,analysis:hit.value,cache:'hit'};if(!camera.directFeedUrl||camera.feedType!=='IMAGE')return{camera,analysis:null,error:'no_machine_readable_snapshot'};try{const response=await timedFetch(camera.directFeedUrl,FRAME_TIMEOUT_MS,{headers:{accept:'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8','user-agent':'SindhornMidtownInternalCameraWeatherLab/1.0'}});if(!response.ok)throw new Error(`frame_http_${response.status}`);const contentType=response.headers.get('content-type')||'';const bytes=new Uint8Array(await response.arrayBuffer());if(!bytes.length||bytes.byteLength>MAX_FRAME_BYTES)throw new Error('frame_size_invalid');const image=decodeImage(bytes,contentType),analysis=analysePixels(camera,image);frameCache.set(key,{expiresAt:now+FRAME_TTL_MS,value:analysis});if(frameCache.size>64){for(const [k,v] of frameCache){if(v.expiresAt<=now)frameCache.delete(k);if(frameCache.size<=48)break}}return{camera,analysis,cache:'miss'} }catch(error){return{camera,analysis:null,error:String((error as Error)?.message||error)}}}
function cameraSummary(results:any[]){const usable=results.filter(item=>item.analysis?.quality==='usable');let weightSum=0,scoreSum=0;for(const item of usable){const d=Math.max(.2,Number(item.camera.distanceKm)||25),weight=1/(1+d/4);weightSum+=weight;scoreSum+=weight*Number(item.analysis.visualRainScore||0)}const score=weightSum?scoreSum/weightSum:null,wet=usable.filter(item=>item.analysis.classification==='wet-candidate'),dry=usable.filter(item=>item.analysis.classification==='dry-candidate');let classification='inconclusive';if(wet.length>=2&&score!==null&&score>=.55)classification='wet-support';else if(dry.length>=3&&wet.length===0&&score!==null&&score<=.24)classification='dry-support';return{classification,visualRainScore:score===null?null:Number(score.toFixed(3)),usableCameraCount:usable.length,wetCandidateCount:wet.length,dryCandidateCount:dry.length,note:'Camera evidence is support-only and is not permitted to override fresh exact-point radar/QPE. Heuristic v1 is intentionally uncalibrated until compared with physical truth observations.'}}

Deno.serve(async(req:Request)=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});if(req.method!=='POST')return json({ok:false,error:'method_not_allowed'},405,origin);const started=performance.now();try{const body=await req.json().catch(()=>null),lat=finite(body?.latitude,-90,90),lon=finite(body?.longitude,-180,180);if(lat===null||lon===null)return json({ok:false,error:'invalid_location'},400,origin);const catalog=await buildCatalog(),ranked=catalog.cameras.map(camera=>({...camera,distanceKm:Number(haversineKm(lat,lon,camera.lat,camera.lon).toFixed(2))})).sort((a,b)=>(a.distanceKm||Infinity)-(b.distanceKm||Infinity));const imageCameras=ranked.filter(camera=>camera.feedType==='IMAGE'&&camera.directFeedUrl).slice(0,MAX_ANALYSED_IMAGE_CAMERAS);const analysed=await mapLimit(imageCameras,4,analyseCamera);return json({ok:true,provider:'bangkok-public-camera-network',kind:'camera-observation-support',fetchedAt:new Date().toISOString(),catalog:{provider:'OpenCCTV public-camera directory',sourceUrl:CATALOG_URL,cache:catalog.cache,totalCameraCount:ranked.length,imageFeedCount:ranked.filter(camera=>camera.feedType==='IMAGE').length,machineReadableSnapshotCount:ranked.filter(camera=>camera.feedType==='IMAGE'&&camera.directFeedUrl).length,liveCount:ranked.filter(camera=>camera.live).length},cameraEvidence:cameraSummary(analysed),nearestCameras:ranked.slice(0,12).map(camera=>({id:camera.id,name:camera.name,distanceKm:camera.distanceKm,feedType:camera.feedType,sourceHost:camera.sourceHost,live:camera.live,refreshText:camera.refreshText,pageUrl:camera.pageUrl,machineReadableSnapshot:Boolean(camera.feedType==='IMAGE'&&camera.directFeedUrl)})),analysedCameras:analysed.map(item=>({id:item.camera.id,name:item.camera.name,distanceKm:item.camera.distanceKm,sourceHost:item.camera.sourceHost,pageUrl:item.camera.pageUrl,analysis:item.analysis,error:item.error||null,cache:item.cache||null})),analysisPolicy:{version:'camera-heuristic-v1-uncalibrated',supportOnly:true,storesRawFrames:false,personOrVehicleRecognition:false,maxAnalysedImageCameras:MAX_ANALYSED_IMAGE_CAMERAS},totalLatencyMs:Math.round(performance.now()-started)},200,origin)}catch(error){return json({ok:false,provider:'bangkok-public-camera-network',error:String((error as Error)?.message||'camera_lab_unavailable'),fetchedAt:new Date().toISOString(),totalLatencyMs:Math.round(performance.now()-started)},502,origin)}});
